name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npm run build
      - uses: peaceiris/gh-pages@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          publish-dir: dist
